apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-processor
  namespace: certaintyai
  labels:
    app: content-processor
    component: processing
spec:
  replicas: 3
  selector:
    matchLabels:
      app: content-processor
  template:
    metadata:
      labels:
        app: content-processor
        component: processing
    spec:
      containers:
        - name: content-processor
          image: certaintyai:latest
          ports:
            - containerPort: 3000
            - containerPort: 9090 # Metrics port
          env:
            - name: SERVICE_TYPE
              value: 'content-processor'
            - name: PORT
              value: '3000'
          envFrom:
            - configMapRef:
                name: certaintyai-config
            - secretRef:
                name: certaintyai-secrets
          resources:
            requests:
              memory: '768Mi'
              cpu: '750m'
            limits:
              memory: '1.5Gi'
              cpu: '1500m'
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: app-logs
              mountPath: /app/logs
            - name: temp-storage
              mountPath: /tmp/processing
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: temp-storage
          emptyDir:
            sizeLimit: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: content-processor-service
  namespace: certaintyai
  labels:
    app: content-processor
spec:
  selector:
    app: content-processor
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: metrics
      port: 9090
      targetPort: 9090
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: content-processor-hpa
  namespace: certaintyai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: content-processor
  minReplicas: 2
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 20
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 75
          periodSeconds: 60
        - type: Pods
          value: 3
          periodSeconds: 60
