// Fact-checking module exports
export * from './interfaces/FactChecker';
export * from './interfaces/KnowledgeBase';
export * from './interfaces/ExternalKnowledgeSource';
export * from './FactChecker';
export * from './MockKnowledgeBase';
export * from './ClaimExtractor';
export * from './SourceCredibilityScorer';
export * from './ExternalSourceManager';
export * from './external-sources/WikipediaSource';
export * from './external-sources/GovernmentDataSource';
